openapi: 3.2.0
info:
  version: 1.0.0
  title: Integration Configurations API
servers:
- url: /services/integration-api/v1
security:
- token: []
tags:
- name: Configurations
paths:
  /configurations:
    get:
      description: Returns a list of available processor configurations
      tags:
      - Configurations
      operationId: getProcessorConfigurations
      parameters:
      - $ref: '#/components/parameters/connectorType'
      - $ref: '#/components/parameters/connectorId'
      - $ref: '#/components/parameters/connectorVersion'
      - $ref: '#/components/parameters/processingDirection'
      - $ref: '#/components/parameters/processingMode'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                $ref: '#/components/schemas/ProcessorConfiguration'
        '403':
          description: The user is not allowed to use this endpoint.
      summary: Get processor configurations
      x-summary-source: derived
    put:
      description: Inserts a new processor configuration or updates an existing one
      tags:
      - Configurations
      operationId: upsertProcessorConfiguration
      responses:
        '204':
          description: Upsert successful.
        '403':
          description: The user is not allowed to use this endpoint.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessorConfiguration'
      summary: Upsert processor configuration
      x-summary-source: derived
    delete:
      description: Delete a single processor configuration
      tags:
      - Configurations
      operationId: deleteProcessorConfiguration
      parameters:
      - $ref: '#/components/parameters/connectorType'
      - $ref: '#/components/parameters/connectorId'
      - $ref: '#/components/parameters/connectorVersion'
      - $ref: '#/components/parameters/processingDirection'
      - $ref: '#/components/parameters/processingMode'
      responses:
        default:
          description: successful operation
        '400':
          description: Not all necessary fields are set in parameters.
        '403':
          description: The user is not allowed to use this endpoint.
        '404':
          description: No such processor configuration found.
        '422':
          description: Could not process the given processor configuration.
      summary: Delete processor configuration
      x-summary-source: derived
components:
  schemas:
    ProcessorConfiguration:
      type: object
      discriminator:
        propertyName: processingDirection
      required:
      - connectorType
      - connectorId
      - connectorVersion
      - processingDirection
      properties:
        connectorType:
          description: The type of connector that is used
          example: lxKubernetes
          type: string
        connectorId:
          description: The identifier of the connector instance
          example: Kub Dev-001
          type: string
        connectorVersion:
          description: The version of the connector that is expected to process this LDIF file
          example: 1.2.0
          type: string
        processingDirection:
          description: The data flow direction, could be [inbound, outbound]
          type: string
          example: inbound
        processingMode:
          description: The processing mode, could be [partial, full]
          type: string
          default: partial
          enum:
          - partial
          - full
        sequentialExecution:
          description: When set to true, all synchronizations runs processed by this processor configuration will be executed sequentially instead of in parallel.
          type: boolean
          default: false
  parameters:
    connectorVersion:
      name: connectorVersion
      description: The version of the connector that is expected to process this LDIF file
      in: query
      required: false
      schema:
        type: string
    processingDirection:
      name: processingDirection
      description: The data flow direction, could be [inbound, outbound]
      in: query
      required: false
      schema:
        type: string
        enum:
        - inbound
        - outbound
    connectorId:
      name: connectorId
      description: The identifier of the connector instance
      in: query
      required: false
      schema:
        type: string
    processingMode:
      name: processingMode
      description: The processing mode, could be [partial, full]
      in: query
      required: false
      schema:
        type: string
        enum:
        - partial
        - full
    connectorType:
      name: connectorType
      description: The type of connector that is used
      in: query
      required: false
      schema:
        type: string
  securitySchemes:
    token:
      type: oauth2
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: /services/mtm/v1/oauth2/token
